version: "3.9"

services:
  db:
    platform: linux/x86_64 
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    restart: always

    environment:
      - "MYSQL_ROOT_PASSWORD=root_strong_password"
      - "MYSQL_DATABASE=reservation_system"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=kaigatsu_lateral"
      - "TZ: Asia/Tokyo"
